apiVersion: apps/v1
kind: Deployment
metadata:
  name: novabank-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: novabank
    component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: novabank
      component: backend
  template:
    metadata:
      labels:
        app: novabank
        component: backend
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: backend
          image: {{ .Values.backend.image | quote }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.backend.secretName }}
