apiVersion: apps/v1
kind: Deployment
metadata:
  name: novabank-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: novabank
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: novabank
      component: frontend
  template:
    metadata:
      labels:
        app: novabank
        component: frontend
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image | quote }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
