apiVersion: apps/v1
kind: Deployment
metadata:
  name: novabank-db
  namespace: {{ .Values.namespace }}
  labels:
    app: novabank-db
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: novabank-db
  template:
    metadata:
      labels:
        app: novabank-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          imagePullPolicy: {{ .Values.postgres.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
              protocol: TCP
          env:
            - name: PGDATA
              value: {{ .Values.postgres.pgdata | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.postgres.persistence.mountPath }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.existingClaim }}
