apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: novabank-security-headers
  namespace: {{ .Values.namespace }}
spec:
  headers:
    contentSecurityPolicy: "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data:; font-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; upgrade-insecure-requests"
    frameDeny: true
    contentTypeNosniff: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customResponseHeaders:
      Server: ""
