[k8s_master]
k8s-master ansible_host=192.168.100.30

[k8s_workers]
k8s-worker-1 ansible_host=192.168.100.31
k8s-worker-2 ansible_host=192.168.100.32

[minio_server]
minio-backup ansible_host=192.168.100.33

[k8s_cluster:children]
k8s_master
k8s_workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
